name: sqflite_tizen
description: Tizen implementation of the sqflite plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/main/packages/sqflite
version: 0.1.6

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: SqflitePlugin
        fileName: sqflite_plugin.h
        dartPluginClass: SqfliteTizen

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.3
