name: firebase_core_tizen
description: Tizen implementation of the firebase_core plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/main/packages/firebase_core
version: 0.2.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  firebase_core_dart: ^1.0.1
  firebase_core_platform_interface: ^8.1.1
  flutter:
    sdk: flutter

flutter:
  plugin:
    implements: firebase_core
    platforms:
      tizen:
        dartPluginClass: FirebaseCore

false_secrets:
  - /example/lib/main.dart
  - /example/lib/firebase_options.dart
