name: permission_handler_tizen
description: Tizen implementation of the permission_handler plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/main/packages/permission_handler
version: 1.4.7

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    implements: permission_handler
    platforms:
      tizen:
        pluginClass: PermissionHandlerTizenPlugin
        fileName: permission_handler_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface: ^4.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
