name: geolocator_tizen
description: Tizen implementation of the geolocator plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/main/packages/geolocator
version: 1.0.11

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    implements: geolocator
    platforms:
      tizen:
        pluginClass: GeolocatorTizenPlugin
        fileName: geolocator_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  geolocator_platform_interface: ^4.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
