name: flutter_inappwebview_tizen
description: Tizen implementation of the flutter_inappwebview plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/flutter_inappwebview
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: FlutterInappwebviewTizenPlugin
        fileName: flutter_inappwebview_tizen_plugin.h
        dartPluginClass: TizenInAppWebViewPlatform

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_platform_interface: ^1.3.0+1
  flutter_tizen: ^0.2.1

topics:
  - html
  - webview
  - webview-flutter
  - inappwebview
  - browser
