name: network_info_plus_tizen
description: Tizen implementation of the network_info_plus plugin
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/main/packages/network_info_plus
version: 1.2.0

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

flutter:
  plugin:
    implements: network_info_plus
    platforms:
      tizen:
        pluginClass: NetworkInfoPlusTizenPlugin
        fileName: network_info_plus_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  network_info_plus_platform_interface: ^3.1.0

dev_dependencies:
  flutter_lints: ">=2.0.1 <4.0.0"
