#ifndef PERMISSION_HANDLER_TYPE_H_
#define PERMISSION_HANDLER_TYPE_H_

// permission group
enum PermissionGroup {
  PERMISSION_GROUP_CALENDAR = 0,
  PERMISSION_GROUP_CAMERA,
  PERMISSION_GROUP_CONTACTS,
  PERMISSION_GROUP_LOCATION,
  PERMISSION_GROUP_LOCATION_ALWAYS,
  PERMISSION_GROUP_LOCATION_WHEN_IN_USE,
  PERMISSION_GROUP_MEDIA_LIBRARY,
  PERMISSION_GROUP_MICROPHONE,
  PERMISSION_GROUP_PHONE,
  PERMISSION_GROUP_PHOTOS,
  PERMISSION_GROUP_REMINDERS,
  PERMISSION_GROUP_SENSORS,
  PERMISSION_GROUP_SMS,
  PERMISSION_GROUP_SPEECH,
  PERMISSION_GROUP_STORAGE,
  PERMISSION_GROUP_IGNORE_BATTERY_OPTIMIZATIONS,
  PERMISSION_GROUP_NOTIFICATION,
  PERMISSION_GROUP_ACCESS_MEDIA_LOCATION,
  PERMISSION_GROUP_ACTIVITY_RECOGNITION,
  PERMISSION_GROUP_UNKNOWN
};

// permission status
enum PermissionStatus {
  PERMISSION_STATUS_DENIED = 0,
  PERMISSION_STATUS_GRANTED,
  PERMISSION_STATUS_RESTRICTED,
  PERMISSION_STATUS_NOT_DETERMINED,
  PERMISSION_STATUS_NEVER_ASK_AGAIN
};

// service status
enum ServiceStatus {
  SERVICE_STATUS_DISABLED = 0,
  SERVICE_STATUS_ENABLED,
  SERVICE_STATUS_NOT_APPLICABLE
};

#endif  // PERMISSION_HANDLER_TYPE_H_