#ifndef PERMISSION_HANDLER_TYPE_H_
#define PERMISSION_HANDLER_TYPE_H_

// permission group
enum PermissionGroup {
  PERMISSION_GROUP_CALENDAR = 0,
  PERMISSION_GROUP_CAMERA = 1,
  PERMISSION_GROUP_CONTACTS = 2,
  PERMISSION_GROUP_LOCATION = 3,
  PERMISSION_GROUP_LOCATION_ALWAYS = 4,
  PERMISSION_GROUP_LOCATION_WHEN_IN_USE = 5,
  PERMISSION_GROUP_MEDIA_LIBRARY = 6,
  PERMISSION_GROUP_MICROPHONE = 7,
  PERMISSION_GROUP_PHONE = 8,
  PERMISSION_GROUP_PHOTOS = 9,
  PERMISSION_GROUP_PHOTOS_ADD_ONLY = 10,
  PERMISSION_GROUP_REMINDERS = 11,
  PERMISSION_GROUP_SENSORS = 12,
  PERMISSION_GROUP_SMS = 13,
  PERMISSION_GROUP_SPEECH = 14,
  PERMISSION_GROUP_STORAGE = 15,
  PERMISSION_GROUP_IGNORE_BATTERY_OPTIMIZATIONS = 16,
  PERMISSION_GROUP_NOTIFICATION = 17,
  PERMISSION_GROUP_ACCESS_MEDIA_LOCATION = 18,
  PERMISSION_GROUP_ACTIVITY_RECOGNITION = 19,
  PERMISSION_GROUP_UNKNOWN = 20,
  PERMISSION_GROUP_BLUETOOTH = 21
};

// permission status
enum PermissionStatus {
  PERMISSION_STATUS_DENIED = 0,
  PERMISSION_STATUS_GRANTED,
  PERMISSION_STATUS_RESTRICTED,
  PERMISSION_STATUS_LIMITED,
  PERMISSION_STATUS_NEVER_ASK_AGAIN
};

// service status
enum ServiceStatus {
  SERVICE_STATUS_DISABLED = 0,
  SERVICE_STATUS_ENABLED,
  SERVICE_STATUS_NOT_APPLICABLE
};

#endif  // PERMISSION_HANDLER_TYPE_H_
