// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart' show calloc;
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'dart:convert' show utf8, jsonEncode, jsonDecode;

import 'package:flutter/foundation.dart'
    show ReadBuffer, WriteBuffer, debugPrint;
import 'package:flutter/services.dart';

class PlayerMessage {
  PlayerMessage({required this.playerId});

  int playerId;

  Object encode() {
    return <Object?>[playerId];
  }

  static PlayerMessage decode(Object result) {
    result as List<Object?>;
    return PlayerMessage(playerId: result[0]! as int);
  }
}

class LoopingMessage {
  LoopingMessage({required this.playerId, required this.isLooping});

  int playerId;

  bool isLooping;

  Object encode() {
    return <Object?>[playerId, isLooping];
  }

  static LoopingMessage decode(Object result) {
    result as List<Object?>;
    return LoopingMessage(
      playerId: result[0]! as int,
      isLooping: result[1]! as bool,
    );
  }
}

class VolumeMessage {
  VolumeMessage({required this.playerId, required this.volume});

  int playerId;

  double volume;

  Object encode() {
    return <Object?>[playerId, volume];
  }

  static VolumeMessage decode(Object result) {
    result as List<Object?>;
    return VolumeMessage(
      playerId: result[0]! as int,
      volume: result[1]! as double,
    );
  }
}

class PlaybackSpeedMessage {
  PlaybackSpeedMessage({required this.playerId, required this.speed});

  int playerId;

  double speed;

  Object encode() {
    return <Object?>[playerId, speed];
  }

  static PlaybackSpeedMessage decode(Object result) {
    result as List<Object?>;
    return PlaybackSpeedMessage(
      playerId: result[0]! as int,
      speed: result[1]! as double,
    );
  }
}

class TrackMessage {
  TrackMessage({required this.playerId, required this.tracks});

  int playerId;

  List<Map<Object?, Object?>?> tracks;

  Object encode() {
    return <Object?>[playerId, tracks];
  }

  static TrackMessage decode(Object result) {
    result as List<Object?>;
    return TrackMessage(
      playerId: result[0]! as int,
      tracks: (result[1] as List<Object?>?)!.cast<Map<Object?, Object?>?>(),
    );
  }
}

class TrackTypeMessage {
  TrackTypeMessage({required this.playerId, required this.trackType});

  int playerId;

  String trackType;

  Object encode() {
    return <Object?>[playerId, trackType];
  }

  static TrackTypeMessage decode(Object result) {
    result as List<Object?>;
    return TrackTypeMessage(
      playerId: result[0]! as int,
      trackType: result[1]! as String,
    );
  }
}

class SelectedTracksMessage {
  SelectedTracksMessage({
    required this.playerId,
    required this.trackId,
    required this.trackType,
  });

  int playerId;

  int trackId;

  String trackType;

  Object encode() {
    return <Object?>[playerId, trackId, trackType];
  }

  static SelectedTracksMessage decode(Object result) {
    result as List<Object?>;
    return SelectedTracksMessage(
      playerId: result[0]! as int,
      trackId: result[1]! as int,
      trackType: result[2]! as String,
    );
  }
}

class PositionMessage {
  PositionMessage({required this.playerId, required this.position});

  int playerId;

  int position;

  Object encode() {
    return <Object?>[playerId, position];
  }

  static PositionMessage decode(Object result) {
    result as List<Object?>;
    return PositionMessage(
      playerId: result[0]! as int,
      position: result[1]! as int,
    );
  }
}

class CreateMessage {
  CreateMessage({
    this.asset,
    this.uri,
    this.packageName,
    this.formatHint,
    this.httpHeaders,
    this.drmConfigs,
    this.playerOptions,
  });

  String? asset;

  String? uri;

  String? packageName;

  String? formatHint;

  Map<Object?, Object?>? httpHeaders;

  Map<Object?, Object?>? drmConfigs;

  Map<Object?, Object?>? playerOptions;

  Object encode() {
    return <Object?>[
      asset,
      uri,
      packageName,
      formatHint,
      httpHeaders,
      drmConfigs,
      playerOptions,
    ];
  }

  static CreateMessage decode(Object result) {
    result as List<Object?>;
    return CreateMessage(
      asset: result[0] as String?,
      uri: result[1] as String?,
      packageName: result[2] as String?,
      formatHint: result[3] as String?,
      httpHeaders:
          (result[4] as Map<Object?, Object?>?)?.cast<Object?, Object?>(),
      drmConfigs:
          (result[5] as Map<Object?, Object?>?)?.cast<Object?, Object?>(),
      playerOptions:
          (result[6] as Map<Object?, Object?>?)?.cast<Object?, Object?>(),
    );
  }
}

class MixWithOthersMessage {
  MixWithOthersMessage({required this.mixWithOthers});

  bool mixWithOthers;

  Object encode() {
    return <Object?>[mixWithOthers];
  }

  static MixWithOthersMessage decode(Object result) {
    result as List<Object?>;
    return MixWithOthersMessage(mixWithOthers: result[0]! as bool);
  }
}

class GeometryMessage {
  GeometryMessage({
    required this.playerId,
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  int playerId;

  int x;

  int y;

  int width;

  int height;

  Object encode() {
    return <Object?>[playerId, x, y, width, height];
  }

  static GeometryMessage decode(Object result) {
    result as List<Object?>;
    return GeometryMessage(
      playerId: result[0]! as int,
      x: result[1]! as int,
      y: result[2]! as int,
      width: result[3]! as int,
      height: result[4]! as int,
    );
  }
}

class DurationMessage {
  DurationMessage({required this.playerId, this.durationRange});

  int playerId;

  List<int?>? durationRange;

  Object encode() {
    return <Object?>[playerId, durationRange];
  }

  static DurationMessage decode(Object result) {
    result as List<Object?>;
    return DurationMessage(
      playerId: result[0]! as int,
      durationRange: (result[1] as List<Object?>?)?.cast<int?>(),
    );
  }
}

class RotationMessage {
  RotationMessage({required this.playerId, required this.rotation});

  int playerId;

  int rotation;

  Object encode() {
    return <Object?>[playerId, rotation];
  }

  static RotationMessage decode(Object result) {
    result as List<Object?>;
    return RotationMessage(
      playerId: result[0]! as int,
      rotation: result[1]! as int,
    );
  }
}

class _VideoPlayerVideoholeApiCodec extends StandardMessageCodec {
  const _VideoPlayerVideoholeApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CreateMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is CreateMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is DurationMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is GeometryMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is LoopingMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is MixWithOthersMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PlaybackSpeedMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is PlayerMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PositionMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is RotationMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is SelectedTracksMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is TrackMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is TrackTypeMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is VolumeMessage) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return CreateMessage.decode(readValue(buffer)!);
      case 129:
        return CreateMessage.decode(readValue(buffer)!);
      case 130:
        return DurationMessage.decode(readValue(buffer)!);
      case 131:
        return GeometryMessage.decode(readValue(buffer)!);
      case 132:
        return LoopingMessage.decode(readValue(buffer)!);
      case 133:
        return MixWithOthersMessage.decode(readValue(buffer)!);
      case 134:
        return PlaybackSpeedMessage.decode(readValue(buffer)!);
      case 135:
        return PlayerMessage.decode(readValue(buffer)!);
      case 136:
        return PositionMessage.decode(readValue(buffer)!);
      case 137:
        return RotationMessage.decode(readValue(buffer)!);
      case 138:
        return SelectedTracksMessage.decode(readValue(buffer)!);
      case 139:
        return TrackMessage.decode(readValue(buffer)!);
      case 140:
        return TrackTypeMessage.decode(readValue(buffer)!);
      case 141:
        return VolumeMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class VideoPlayerVideoholeApi {
  /// Constructor for [VideoPlayerVideoholeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VideoPlayerVideoholeApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _VideoPlayerVideoholeApiCodec();

  Future<void> initialize() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.initialize',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<PlayerMessage> create(CreateMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.create',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as PlayerMessage?)!;
    }
  }

  Future<void> dispose(PlayerMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.dispose',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setLooping(LoopingMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.setLooping',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setVolume(VolumeMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.setVolume',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setPlaybackSpeed(PlaybackSpeedMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.setPlaybackSpeed',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> play(PlayerMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.play',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> setDeactivate(PlayerMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.setDeactivate',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }

  Future<bool> setActivate(PlayerMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.setActivate',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }

  Future<TrackMessage> track(TrackTypeMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.track',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as TrackMessage?)!;
    }
  }

  Future<bool> setTrackSelection(SelectedTracksMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.setTrackSelection',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }

  Future<PositionMessage> position(PlayerMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.position',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as PositionMessage?)!;
    }
  }

  Future<void> seekTo(PositionMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.seekTo',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> pause(PlayerMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.pause',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setMixWithOthers(MixWithOthersMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.setMixWithOthers',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setDisplayGeometry(GeometryMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.setDisplayGeometry',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<DurationMessage> duration(PlayerMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.duration',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as DurationMessage?)!;
    }
  }

  Future<void> suspend(int arg_playerId) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.suspend',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_playerId]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> restore(
    int arg_playerId,
    CreateMessage? arg_msg,
    int arg_resumeTime,
  ) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.restore',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_playerId, arg_msg, arg_resumeTime])
            as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> setDisplayRotate(RotationMessage arg_msg) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      'dev.flutter.pigeon.video_player_videohole.VideoPlayerVideoholeApi.setDisplayRotate',
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_msg]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }
}

// ===== FFI Section - Gradual Migration =====

// FFI type definitions
typedef _FFIInitializeNative = ffi.Int32 Function();
typedef _FFIInitializeDart = int Function();

// FFI type definitions - create takes a single JSON string for all parameters
// JSON format: {"uri":"...","asset":"...","packageName":"...","formatHint":"...",
//               "httpHeaders":{...},"drmConfigs":{...},"playerOptions":{...}}
typedef _FFICreateNative = ffi.Int64 Function(ffi.Pointer<ffi.Char>);
typedef _FFICreateDart = int Function(ffi.Pointer<ffi.Char>);

// FFI type definitions for additional methods
typedef _FFIDisposeNative = ffi.Int32 Function(ffi.Int64);
typedef _FFIDisposeDart = int Function(int);

typedef _FFIPlayNative = ffi.Int32 Function(ffi.Int64);
typedef _FFIPlayDart = int Function(int);

typedef _FFIPauseNative = ffi.Int32 Function(ffi.Int64);
typedef _FFIPauseDart = int Function(int);

typedef _FFISeekToNative = ffi.Int32 Function(ffi.Int64, ffi.Int64);
typedef _FFISeekToDart = int Function(int, int);

typedef _FFIGetPositionNative = ffi.Int64 Function(ffi.Int64);
typedef _FFIGetPositionDart = int Function(int);

typedef _FFIGetDurationNative = ffi.Pointer<ffi.Char> Function(ffi.Int64);
typedef _FFIGetDurationDart = ffi.Pointer<ffi.Char> Function(int);

typedef _FFISetVolumeNative = ffi.Int32 Function(ffi.Int64, ffi.Double);
typedef _FFISetVolumeDart = int Function(int, double);

typedef _FFISetPlaybackSpeedNative = ffi.Int32 Function(ffi.Int64, ffi.Double);
typedef _FFISetPlaybackSpeedDart = int Function(int, double);

typedef _FFISetLoopingNative = ffi.Int32 Function(ffi.Int64, ffi.Bool);
typedef _FFISetLoopingDart = int Function(int, bool);

typedef _FFIGetTrackInfoNative = ffi.Pointer<ffi.Char> Function(
    ffi.Int64, ffi.Pointer<ffi.Char>);
typedef _FFIGetTrackInfoDart = ffi.Pointer<ffi.Char> Function(
    int, ffi.Pointer<ffi.Char>);

typedef _FFISetTrackSelectionNative = ffi.Int32 Function(
    ffi.Int64, ffi.Int64, ffi.Pointer<ffi.Char>);
typedef _FFISetTrackSelectionDart = int Function(
    int, int, ffi.Pointer<ffi.Char>);

typedef _FFISetDisplayGeometryNative = ffi.Int32 Function(
    ffi.Int64, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32);
typedef _FFISetDisplayGeometryDart = int Function(int, int, int, int, int);

typedef _FFISetDisplayRotateNative = ffi.Int32 Function(ffi.Int64, ffi.Int32);
typedef _FFISetDisplayRotateDart = int Function(int, int);

typedef _FFISuspendNative = ffi.Int32 Function(ffi.Int64);
typedef _FFISuspendDart = int Function(int);

typedef _FFIRestoreNative = ffi.Int32 Function(
    ffi.Int64, ffi.Pointer<ffi.Char>, ffi.Int64);
typedef _FFIRestoreDart = int Function(int, ffi.Pointer<ffi.Char>, int);

// Helper functions for FFI string conversion
ffi.Pointer<ffi.Char> _toPointer(String? str) {
  if (str == null) return ffi.nullptr;
  final units = utf8.encode(str);
  final result = calloc.allocate<ffi.Uint8>(units.length + 1);
  final Uint8List nativeString = result.asTypedList(units.length + 1);
  nativeString.setAll(0, units);
  nativeString[units.length] = 0; // null terminator
  return result.cast<ffi.Char>();
}

void _freePointer(ffi.Pointer<ffi.Char> ptr) {
  if (ptr != ffi.nullptr) {
    calloc.free(ptr);
  }
}

/// FFI Bindings for video_player_tizen
class VideoPlayerFFIBindings {
  static VideoPlayerFFIBindings? _instance;
  ffi.DynamicLibrary? _lib;

  late int Function() _ffiInitialize;
  late int Function(ffi.Pointer<ffi.Char>) _ffiCreate;

  late int Function(int) _ffiDispose;
  late int Function(int) _ffiPlay;
  late int Function(int) _ffiPause;
  late int Function(int, int) _ffiSeekTo;
  late int Function(int) _ffiGetPosition;
  late ffi.Pointer<ffi.Char> Function(int) _ffiGetDuration;
  late int Function(int, double) _ffiSetVolume;
  late int Function(int, double) _ffiSetPlaybackSpeed;
  late int Function(int, bool) _ffiSetLooping;
  late ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)
      _ffiGetTrackInfo;
  late int Function(int, int, ffi.Pointer<ffi.Char>) _ffiSetTrackSelection;
  late int Function(int, int, int, int, int) _ffiSetDisplayGeometry;
  late int Function(int, int) _ffiSetDisplayRotate;
  late int Function(int) _ffiSuspend;
  late int Function(int, ffi.Pointer<ffi.Char>, int) _ffiRestore;

  static VideoPlayerFFIBindings get instance {
    _instance ??= VideoPlayerFFIBindings._();
    return _instance!;
  }

  VideoPlayerFFIBindings._();

  /// Load the native library - must be called before using FFI functions
  void load() {
    if (_lib != null) return;

    try {
      // On Tizen, the plugin is statically linked, so we use process() to access
      // symbols from the main executable
      _lib = ffi.DynamicLibrary.process();

      _ffiInitialize = _lib!
          .lookup<ffi.NativeFunction<_FFIInitializeNative>>('ffi_initialize')
          .asFunction<_FFIInitializeDart>();

      _ffiCreate = _lib!
          .lookup<ffi.NativeFunction<_FFICreateNative>>('ffi_create')
          .asFunction<_FFICreateDart>();

      _ffiDispose = _lib!
          .lookup<ffi.NativeFunction<_FFIDisposeNative>>('ffi_dispose')
          .asFunction<_FFIDisposeDart>();

      _ffiPlay = _lib!
          .lookup<ffi.NativeFunction<_FFIPlayNative>>('ffi_play')
          .asFunction<_FFIPlayDart>();

      _ffiPause = _lib!
          .lookup<ffi.NativeFunction<_FFIPauseNative>>('ffi_pause')
          .asFunction<_FFIPauseDart>();

      _ffiSeekTo = _lib!
          .lookup<ffi.NativeFunction<_FFISeekToNative>>('ffi_seek_to')
          .asFunction<_FFISeekToDart>();

      _ffiGetPosition = _lib!
          .lookup<ffi.NativeFunction<_FFIGetPositionNative>>('ffi_get_position')
          .asFunction<_FFIGetPositionDart>();

      _ffiGetDuration = _lib!
          .lookup<ffi.NativeFunction<_FFIGetDurationNative>>('ffi_get_duration')
          .asFunction<_FFIGetDurationDart>();

      _ffiSetVolume = _lib!
          .lookup<ffi.NativeFunction<_FFISetVolumeNative>>('ffi_set_volume')
          .asFunction<_FFISetVolumeDart>();

      _ffiSetPlaybackSpeed = _lib!
          .lookup<ffi.NativeFunction<_FFISetPlaybackSpeedNative>>(
              'ffi_set_playback_speed')
          .asFunction<_FFISetPlaybackSpeedDart>();

      _ffiSetLooping = _lib!
          .lookup<ffi.NativeFunction<_FFISetLoopingNative>>('ffi_set_looping')
          .asFunction<_FFISetLoopingDart>();

      _ffiGetTrackInfo = _lib!
          .lookup<ffi.NativeFunction<_FFIGetTrackInfoNative>>(
              'ffi_get_track_info')
          .asFunction<_FFIGetTrackInfoDart>();

      _ffiSetTrackSelection = _lib!
          .lookup<ffi.NativeFunction<_FFISetTrackSelectionNative>>(
              'ffi_set_track_selection')
          .asFunction<_FFISetTrackSelectionDart>();

      _ffiSetDisplayGeometry = _lib!
          .lookup<ffi.NativeFunction<_FFISetDisplayGeometryNative>>(
              'ffi_set_display_geometry')
          .asFunction<_FFISetDisplayGeometryDart>();

      _ffiSetDisplayRotate = _lib!
          .lookup<ffi.NativeFunction<_FFISetDisplayRotateNative>>(
              'ffi_set_display_rotate')
          .asFunction<_FFISetDisplayRotateDart>();

      _ffiSuspend = _lib!
          .lookup<ffi.NativeFunction<_FFISuspendNative>>('ffi_suspend')
          .asFunction<_FFISuspendDart>();

      _ffiRestore = _lib!
          .lookup<ffi.NativeFunction<_FFIRestoreNative>>('ffi_restore')
          .asFunction<_FFIRestoreDart>();

      debugPrint('FFI bindings loaded successfully');
    } catch (e) {
      debugPrint('Failed to load FFI bindings: $e');
      rethrow;
    }
  }

  bool get isLoaded => _lib != null;

  /// FFI initialize function
  int ffiInitialize() {
    if (!isLoaded) {
      throw StateError('FFI bindings not loaded. Call load() first.');
    }
    return _ffiInitialize();
  }

  /// FFI create function - takes a single JSON string for all parameters
  /// JSON format: {"uri":"...","asset":"...","packageName":"...","formatHint":"...",
  ///               "httpHeaders":{...},"drmConfigs":{...},"playerOptions":{...}}
  int ffiCreate({
    String? uri,
    String? asset,
    String? packageName,
    String? formatHint,
    Map<Object?, Object?>? httpHeaders,
    Map<Object?, Object?>? drmConfigs,
    Map<Object?, Object?>? playerOptions,
  }) {
    if (!isLoaded) {
      throw StateError('FFI bindings not loaded. Call load() first.');
    }

    // Build JSON string from individual parameters (same as restore pattern)
    final Map<String, dynamic> jsonMap = <String, dynamic>{};
    if (uri != null && uri.isNotEmpty) jsonMap['uri'] = uri;
    if (asset != null && asset.isNotEmpty) jsonMap['asset'] = asset;
    if (packageName != null && packageName.isNotEmpty)
      jsonMap['packageName'] = packageName;
    if (formatHint != null && formatHint.isNotEmpty)
      jsonMap['formatHint'] = formatHint;
    if (httpHeaders != null && httpHeaders.isNotEmpty)
      jsonMap['httpHeaders'] = httpHeaders;
    if (drmConfigs != null && drmConfigs.isNotEmpty)
      jsonMap['drmConfigs'] = drmConfigs;
    if (playerOptions != null && playerOptions.isNotEmpty)
      jsonMap['playerOptions'] = playerOptions;

    final String jsonString = jsonEncode(jsonMap);
    final jsonPtr = _toPointer(jsonString);

    try {
      return _ffiCreate(jsonPtr);
    } finally {
      _freePointer(jsonPtr);
    }
  }
}

// FFI API for video_player_tizen - mirrors VideoPlayerVideoholeApi structure
// Note: All methods are synchronous for better performance
class VideoPlayerFFIApi {
  int initialize() {
    return ffiInitialize();
  }

  int create({
    String? uri,
    String? asset,
    String? packageName,
    String? formatHint,
    Map<Object?, Object?>? httpHeaders,
    Map<Object?, Object?>? drmConfigs,
    Map<Object?, Object?>? playerOptions,
  }) {
    return ffiCreate(
      uri: uri,
      asset: asset,
      packageName: packageName,
      formatHint: formatHint,
      httpHeaders: httpHeaders,
      drmConfigs: drmConfigs,
      playerOptions: playerOptions,
    );
  }

  int dispose(int playerId) {
    return ffiDispose(playerId);
  }

  int play(int playerId) {
    return ffiPlay(playerId);
  }

  int pause(int playerId) {
    return ffiPause(playerId);
  }

  int seekTo(int playerId, int positionMs) {
    return ffiSeekTo(playerId, positionMs);
  }

  int getPosition(int playerId) {
    return ffiGetPosition(playerId);
  }

  DurationMessage duration(int playerId) {
    return ffiGetDuration(playerId);
  }

  int setVolume(int playerId, double volume) {
    return ffiSetVolume(playerId, volume);
  }

  int setPlaybackSpeed(int playerId, double speed) {
    return ffiSetPlaybackSpeed(playerId, speed);
  }

  int setLooping(int playerId, bool isLooping) {
    return ffiSetLooping(playerId, isLooping);
  }

  int setDisplayGeometry(int playerId, int x, int y, int width, int height) {
    return ffiSetDisplayGeometry(playerId, x, y, width, height);
  }

  int setDisplayRotate(int playerId, int rotation) {
    return ffiSetDisplayRotate(playerId, rotation);
  }

  int suspend(int playerId) {
    return ffiSuspend(playerId);
  }

  int restore(int playerId, String? createMessageJson, int resumeTime) {
    return ffiRestore(playerId, createMessageJson, resumeTime);
  }
}

// Top-level FFI functions for easy access (synchronous)
int ffiInitialize() {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings.ffiInitialize();
}

/// FFI create function - returns player_id or -1 on error
int ffiCreate({
  String? uri,
  String? asset,
  String? packageName,
  String? formatHint,
  Map<Object?, Object?>? httpHeaders,
  Map<Object?, Object?>? drmConfigs,
  Map<Object?, Object?>? playerOptions,
}) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings.ffiCreate(
    uri: uri,
    asset: asset,
    packageName: packageName,
    formatHint: formatHint,
    httpHeaders: httpHeaders,
    drmConfigs: drmConfigs,
    playerOptions: playerOptions,
  );
}

/// FFI dispose function - releases player resources
/// Returns: 0 on success, -1 on error
int ffiDispose(int playerId) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiDispose(playerId);
}

/// FFI play function - starts or resumes playback
/// Returns: 0 on success, -1 on error
int ffiPlay(int playerId) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiPlay(playerId);
}

/// FFI pause function - pauses playback
/// Returns: 0 on success, -1 on error
int ffiPause(int playerId) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiPause(playerId);
}

/// FFI seek_to function - seeks to a specific position (in milliseconds)
/// Returns: 0 on success, -1 on error
int ffiSeekTo(int playerId, int positionMs) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiSeekTo(playerId, positionMs);
}

/// FFI get_position function - gets current playback position in milliseconds
/// Returns: position in milliseconds (>= 0) on success, -1 on error
int ffiGetPosition(int playerId) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiGetPosition(playerId);
}

/// FFI get_duration function - gets video duration range in milliseconds
/// Returns: DurationMessage with durationRange on success
/// For live streams, start may be non-zero
/// Note: The C++ function returns a strdup-allocated string that we must free
DurationMessage ffiGetDuration(int playerId) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  final ptr = bindings._ffiGetDuration(playerId);
  if (ptr == ffi.nullptr) {
    throw Exception('FFI getDuration failed - returned null pointer');
  }
  try {
    // Convert C string to Dart string by finding null terminator
    final bytes = ptr.cast<ffi.Uint8>();
    int length = 0;
    while (bytes[length] != 0) {
      length++;
    }
    final jsonString = utf8.decode(bytes.asTypedList(length));
    if (jsonString == '-1') {
      throw Exception('FFI getDuration failed');
    }
    final Map<String, dynamic> jsonMap = jsonDecode(jsonString);
    return DurationMessage(
      playerId: playerId,
      durationRange: [
        jsonMap['start'] as int,
        jsonMap['end'] as int,
      ],
    );
  } finally {
    // Free the strdup-allocated memory to prevent memory leak
    calloc.free(ptr);
  }
}

/// FFI set_volume function - sets playback volume (0.0 to 1.0)
/// Returns: 0 on success, -1 on error
int ffiSetVolume(int playerId, double volume) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiSetVolume(playerId, volume);
}

/// FFI set_playback_speed function - sets playback speed
/// Returns: 0 on success, -1 on error
int ffiSetPlaybackSpeed(int playerId, double speed) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiSetPlaybackSpeed(playerId, speed);
}

/// FFI set_looping function - enables or disables looping
/// Returns: 0 on success, -1 on error
int ffiSetLooping(int playerId, bool isLooping) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiSetLooping(playerId, isLooping);
}

/// FFI set_display_geometry function - sets the display geometry (ROI)
/// Returns: 0 on success, -1 on error
int ffiSetDisplayGeometry(int playerId, int x, int y, int width, int height) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiSetDisplayGeometry(playerId, x, y, width, height);
}

/// FFI set_display_rotate function - sets display rotation
/// Returns: 0 on success, -1 on error
int ffiSetDisplayRotate(int playerId, int rotation) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiSetDisplayRotate(playerId, rotation);
}

/// FFI suspend function - suspends the player
/// Returns: 0 on success, -1 on error
int ffiSuspend(int playerId) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  return bindings._ffiSuspend(playerId);
}

/// FFI restore function - restores a suspended player
/// Returns: 0 on success, -1 on error
/// createMessageJson: JSON string of CreateMessage or null/empty for using saved state from Suspend
int ffiRestore(int playerId, String? createMessageJson, int resumeTime) {
  final bindings = VideoPlayerFFIBindings.instance;
  if (!bindings.isLoaded) {
    bindings.load();
  }
  // Pass JSON string to C++ for parsing
  final createMessagePtr = _toPointer(createMessageJson);
  try {
    return bindings._ffiRestore(playerId, createMessagePtr, resumeTime);
  } finally {
    _freePointer(createMessagePtr);
  }
}
