# Follows the analysis options of the frontend plugin:
# https://github.com/dlutton/flutter_tts/blob/master/analysis_options.yaml
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - 'build/**'
    - 'android/**'
    - 'ios/**'
    - 'web/**'
    - 'windows/**'
    - 'macos/**'
    - 'linux/**'
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
